
exclude = [
    ".git"
]

include = [
    "src/**/*.py",
    "tests/**/*.py",
    "tasks/**/*.py"
]


# Without E501, ruff will not check for line length
line-length = 120
lint.extend-select = ["E501"]

indent-width = 4

[format]
quote-style = "double"
indent-style = "space"

docstring-code-format = true
