---

- name: Register Current User
  ansible.builtin.set_fact:
    host_user: "{{ ansible_env.USER }}"
  when: host_user is not defined

- name: Run whoami
  ansible.builtin.debug:
    msg: "whoami: {{ host_user }}"
