---
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Run playbook
  ansible.builtin.import_playbook: ../../main.yml
