---

- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

- name: "Prepare Collection"
  hosts: "localhost"
  connection: "local"
  tasks:
    - name: "Run ansible-galaxy"
      ansible.builtin.command: "ansible-galaxy install --force -r ../../requirements.yml"
      changed_when: false

- ansible.builtin.import_playbook: ../../main.yml
