---
dependency:
  name: galaxy
  # options:
  #   requirements-file: ./requirements.yml
  #   # force: true

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: doto-focal64
    box: ubuntu/focal64

provisioner:
  name: ansible
  log: true
  # config_options:
  #   defaults:
  #     host_key_checking: false

verifier:
  name: ansible
