---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check python version
      ansible.builtin.command: python3 --version
      register: python_version
    - name: Assert python version
      ansible.builtin.assert:
        that:
          - "'Python 3' in python_version.stdout"
