---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - geerlingguy.pip
    - devsec.hardening.ssh_hardening
  vars:
    ssh_server_ports: ["22"]
    ssh_allow_tcp_forwarding: "yes"
    sftp_enabled: true
    ssh_custom_options:
      - "Include /etc/ssh/ssh_config.d/*"

  tasks:
    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
