---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Install ssh server with apt
      apt:
        name: openssh-server
        state: present

  roles:
    - role: pwlesssudo
    - role: geerlingguy.pip
    # - role: geerlingguy.docker
    # - role: devsec.hardening.ssh_hardening
    #   vars:
    #     ssh_server_ports: ["22"]
    #     ssh_allow_tcp_forwarding: "yes"
    #     sftp_enabled: true
    #     ssh_custom_options:
    #       - "Include /etc/ssh/ssh_config.d/*"

  tasks:
    # - name: Set authorized key
    #   authorized_key:
    #     user: "{{ ansible_env.USER }}"
    #     state: present
    #     key: https://github.com/tigitlabs.keys

    # - import_tasks: tasks/extra-packages.yml
    #   tags: ['extra-packages']

    - name: Run passwordless sudo role
      include_role:
        name: pwlesssudo
      tags: ['dev']
