---
- name: Configure host.
  hosts: all
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Run whoami
      ansible.builtin.import_tasks: tasks/whoami.yml
      tags: ["always"]

    - name: Install ssh server with apt
      apt:
        name: openssh-server
        state: present
        update_cache: true
      tags: ["never"]

  roles:
    - role: tigitlabs.doto_collection.github_cli
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      vars:
        docker_service_state: started
        docker_users: "{{ ansible_env.USER }}"
    - role: devsec.hardening.ssh_hardening
      vars:
        ssh_server_ports: ["22"]
        ssh_allow_tcp_forwarding: "yes"
        sftp_enabled: true
        ssh_custom_options:
          - "Include /etc/ssh/ssh_config.d/*"

  tasks:
    - name: Set authorized key
      authorized_key:
        user: "{{ ansible_env.USER }}"
        state: present
        key: https://github.com/tigitlabs.keys

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
