---

- name: Configure host.
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags: ["always"]

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Install ssh server with apt
      apt:
        name: openssh-server
        state: present
        update_cache: true
      tags: ["never"]

  roles:
    - role: geerlingguy.pip

    - role: geerlingguy.docker
      vars:
        docker_service_state: started
        docker_users: "{{ ansible_env.USER }}"

    - role: devsec.hardening.ssh_hardening
      vars:
        ssh_server_ports: ["22"]
        ssh_allow_tcp_forwarding: "yes"
        sftp_enabled: true
        ssh_custom_options:
          - "Include /etc/ssh/ssh_config.d/*"

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
