---

- name: Run user tasks.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Run whoami
      ansible.builtin.import_tasks: tasks/whoami.yml
      tags: ["always"]

  tasks:
    - name: Set authorized key
      authorized_key:
        user: "{{ ansible_env.USER }}"
        state: present
        key: https://github.com/tigitlabs.keys
