---
name: Docker Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
  schedule:
    - cron: "0 7 * * 0"

jobs:

  build_and_test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
      - name: Install invoke
        run: sudo apt update && sudo apt install pipx -y && pipx install invoke
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: invoke docker.build
      - name: Test Docker Image
        run: invoke docker.test
